name: code2class

seed: 9
num_workers: 2
log_offline: false

num_classes: 5

# data keys
data_folder: data
vocabulary_name: vocabulary.pkl
train_holdout: train
val_holdout: val
test_holdout: test

save_every_epoch: 1
val_every_epoch: 1
val_check_interval: 0.01
log_every_n_steps: 200
progress_bar_refresh_rate: 1

hyper_parameters:
  n_epochs: 3000
  patience: 10
  batch_size: 16
  test_batch_size: 512
  clip_norm: 5
  max_context: 200
  random_context: true
  shuffle_data: true

  optimizer: "Momentum"
  nesterov: true
  learning_rate: 0.01
  weight_decay: 0
  decay_gamma: 0.95

dataset:
  dir: paths
  name: poj_104
  target:
    max_parts: 1
    is_wrapped: false
    is_splitted: false
    vocabulary_size: 27000
  token:
    max_parts: 5
    is_wrapped: false
    is_splitted: true
    vocabulary_size: 190000
  path:
    max_parts: 9
    is_wrapped: false
    is_splitted: true
    vocabulary_size: null

encoder:
  model: code2class
  embedding_size: 16
  rnn_size: 16
  use_bi_rnn: true
  embedding_dropout: 0.25
  rnn_num_layers: 1
  rnn_dropout: 0.5

classifier:
  n_hidden_layers: 2
  hidden_size: 16
  classifier_input_size: 16
  activation: relu

ssl:
  name: BYOL
  learning_rate: 0.2
  weight_decay: 1.5e-6
  input_height: 32
  batch_size: 32
  num_workers: -1
  warmup_epochs: 10
  max_epochs: 1000