name: gnn

seed: 9
num_workers: 8
log_offline: false

num_classes: 128

# data keys
data_folder: data
train_holdout: train
val_holdout: val
test_holdout: test

save_every_epoch: 1
val_every_epoch: 1
val_check_interval: 0.5
log_every_n_steps: 200
progress_bar_refresh_rate: 1

hyper_parameters:
  n_epochs: 10
  patience: 1
  batch_size: 80
  test_batch_size: 80
  clip_norm: 1
  shuffle_data: true

dataset:
  name: codeforces
  vocab_file: vocab.json
  dir: graphs

encoder:
  embedding_size: 128
  hidden_size: 128
  num_layers: 6
  out_channels: 128

ssl:
  # Name of SSL method
  name: MocoV2
  # SSL method hyperparams
  num_negatives: 15360
  encoder_momentum: 0.999
  softmax_temperature: 0.07
  use_mlp: False
  # Optimizer params
  warmup_epochs: 1
  start_lr: 0.
  learning_rate: 0.03
  weight_decay: 1e-4
  exclude_bn_bias: False