name: gnn

seed: 9
num_workers: 2
log_offline: false

num_classes: 5

# data keys
data_folder: data
train_holdout: train
val_holdout: val
test_holdout: test

save_every_epoch: 1
val_every_epoch: 1
val_check_interval: 0.01
log_every_n_steps: 200
progress_bar_refresh_rate: 1

hyper_parameters:
  n_epochs: 10
  patience: 10
  batch_size: 16
  test_batch_size: 512
  clip_norm: 5
  shuffle_data: true

dataset:
  name: poj_104
  vocab_file: vocab.json
  dir: graphs

encoder:
  embedding_size: 8
  hidden_size: 8
  num_layers: 2
  out_channels: 8

ssl:
  name: BYOL
  learning_rate: 0.2
  weight_decay: 1.5e-6
  input_height: 32
  batch_size: 32
  num_workers: -1
  warmup_epochs: 10
  max_epochs: 1000