name: code2class

seed: 9
num_workers: 8
log_offline: false

num_classes: 128

# data keys
data_folder: data
vocabulary_name: vocabulary.pkl
train_holdout: train
val_holdout: val
test_holdout: test

save_every_epoch: 1
val_every_epoch: 1
val_check_interval: 0.5
log_every_n_steps: 200
progress_bar_refresh_rate: 1

hyper_parameters:
  n_epochs: 5
  patience: 1
  batch_size: 80
  test_batch_size: 80
  clip_norm: 1

dataset:
  dir: paths
  name: codeforces

  max_context: 200
  random_context: true

  max_label_parts: 1
  max_labels: 100000

  max_token_parts: 5
  max_tokens: 20000

  path_length: 9

encoder:
  model: code2class
  embedding_size: 128
  encoder_rnn_size: 128
  encoder_dropout: 0.25
  rnn_num_layers: 1
  classifier_size: 128
  use_bi_rnn: true

classifier:
  classifier_layers: 2
  classifier_size: 128
  activation: relu

ssl:
  # Name of SSL method
  name: SimCLR
  # Training params
  gpus: 1
  num_nodes: 1
   # SSL method hyperparams
  temperature: 0.1
  # Optimizer params
  warmup_epochs: 1
  start_lr: 0.
  learning_rate: 1e-3
  weight_decay: 1e-6
  exclude_bn_bias: False