name: gnn

seed: 9
num_workers: 8
log_offline: false

num_classes: 128

# data keys
data_folder: data
train_holdout: train
val_holdout: val
test_holdout: test

joern_path: joern
script_path: preprocess/joern

save_every_epoch: 1
val_every_epoch: 1
val_check_interval: 0.5
log_every_n_steps: 200
progress_bar_refresh_rate: 1

hyper_parameters:
  n_epochs: 8
  patience: 1
  batch_size: 80
  test_batch_size: 80
  clip_norm: 1
  shuffle_data: true

dataset:
  dir: graphs
  vocab_file: vocab.json
  name: codeforces

encoder:
  embedding_size: 128
  hidden_size: 128
  num_layers: 6
  out_channels: 128

ssl:
  # Name of SSL method
  name: SwAV
  # Training params
  gpus: 1
  num_nodes: 1
  # SSL method hyperparams
  hidden_mlp: 128
  feat_dim: 128
  epsilon: 0.05
  normalize: True
  nmb_prototypes: 1000
  freeze_prototypes_epochs: 1
  temperature: 0.1
  sinkhorn_iterations: 3
  # Optimizer params
  warmup_epochs: 1
  start_lr: 0.
  learning_rate: 1e-3
  weight_decay: 1e-6
  exclude_bn_bias: False