name: transformer

seed: 9
num_workers: 8
log_offline: false

num_classes: 128

# data keys
data_folder: data
train_holdout: train
val_holdout: val
test_holdout: test

save_every_epoch: 1
val_every_epoch: 1
val_check_interval: 0.05
log_every_n_steps: 200
progress_bar_refresh_rate: 1

hyper_parameters:
  n_epochs: 2
  patience: 1
  batch_size: 80
  test_batch_size: 80
  clip_norm: 1
  shuffle_data: true

dataset:
  dir: raw
  name: poj_104
  tokenizer_name: model.yttm
  vocab_size: 20000
  pad_id: 0
  unk_id: 1
  bos_id: 2
  eos_id: 3

encoder:
  hidden_size: 128
  num_classes: 128
  vocab_size: 20000
  num_heads: 2
  num_layers: 2
  dim_feedforward: 1024
  max_seq_len: 384

ssl:
  # Name of SSL method
  name: SwAV
  # Training params
  gpus: 1
  num_nodes: 1
  # SSL method hyperparams
  hidden_mlp: 128
  feat_dim: 128
  epsilon: 0.05
  normalize: True
  nmb_prototypes: 100
  freeze_prototypes_epochs: 1
  temperature: 0.1
  sinkhorn_iterations: 3
  # Optimizer params
  warmup_epochs: 1
  start_lr: 0.
  learning_rate: 1e-3
  weight_decay: 1e-6
  exclude_bn_bias: False