name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with Flake
      run: |
        flake8 --max-line-length=120 --exclude="test_*.py" .
    - name: Test with pytest
      run: |
        pytest . -vv
