name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.1+cpu.html
        pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.1+cpu.html
        pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.1+cpu.html
        pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.7.1+cpu.html
        pip install torch-geometric
    - name: Install yttm
      run: |
        sh scripts/install_yttm.sh
    - name: Lint with Flake
      run: |
        flake8 --max-line-length=120 --exclude="test_*.py","build" .
    - name: Test with pytest
      run: |
        pytest . -vv
